services:
  backend:
    build:
      context: ./backend
    container_name: backend-1
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    
    container_name: frontend-1
    stdin_open: true
    tty: true